### ISSUE TITLE
Pieces Os isn't working in my Garuda

### ISSUE THREAD

**Issue by CharlysFarias03** [pieces-app/obsidian-pieces#10]
Hey, I'm trying to use this plugin, but for some reason the Pieces Os isn't working properly. I use linux in my pc (Garuda, to be more specific). The Pieces for Developers are working fine and nice. So I don't uderstand what's the problem. Could you help me?

**Comment by mason-at-pieces** [comment]
Hey @CharlysFarias03, sorry for such a late reply but I wanted to see if you are still encountering this issue!

**Comment by caleb-at-pieces** [comment]
@CharlysFarias03  I believe I fixed this one a few weeks ago, we had an incorrect port number hard coded on linux. Thank you for creating an issue about this! I'm going to go ahead and close this now, let me know if it's still broken!

**Comment by CharlysFarias03** [comment]
Now this are working nicely
