### ISSUE TITLE
Problem with Linter plugin setting display

### ISSUE THREAD

**Issue by nhan000** [pieces-app/obsidian-pieces#11]
Linter setting when Pieces plugin is off
![image](https://github.com/pieces-app/obsidian-pieces/assets/85216095/9c255698-3739-4339-ae90-97c6e7d96618)

Linter setting when Pieces plugin is on
![image](https://github.com/pieces-app/obsidian-pieces/assets/85216095/b70b58f0-a009-4ae9-b2c6-cc16ff493408)

Related to https://github.com/pieces-app/obsidian-pieces/issues/9#issuecomment-1642583920?

**Comment by caleb-at-pieces** [comment]
@nhan000 is this still happening for you?

**Comment by nhan000** [comment]
Yes

**Comment by caleb-at-pieces** [comment]
Hello, so sorry for the late response on this. I believe this issue has been fixed by version 1.5.1. Going to close this issue now, please let me know if it is still broken! Thank you for reaching out about this.
