### ISSUE TITLE
Pieces CoPilot gives ERROR: message generation in progress. Please wait a few seconds.

### ISSUE THREAD

**Issue by ajkdrag** [pieces-app/obsidian-pieces#12]
Often times, when I query the copilot and it responds with some code and sample output, any follow-up question throws this error, and the only way to move forward is to 'clear chat' and restart the conversation.

**Comment by mason-at-pieces** [comment]
Hey @ajkdrag, sorry for such a late reply on this!

Are you still having this issue? We've updated the plugin quite a lot since you first sent this so just want to confirm that this is still happening.

**Comment by caleb-at-pieces** [comment]
Going to go ahead and close this for the lack of activity, if the issue is still happening @ajkdrag please do reopen this thread.
