### ISSUE TITLE
Pieces Copy button bug

### ISSUE THREAD

**Issue by ajkdrag** [pieces-app/obsidian-pieces#13]
When I click the copy button multiple times, it creates something like this:
![image](https://github.com/pieces-app/obsidian-pieces/assets/40544701/ffa56c49-c821-4da0-ae99-0bf8160ba9d8)

Ideally, however many times I copy, it shouldn't keep on wrapping up the code in the markdown code block iteratively.
Maybe fix this by assigning to a new variable instead of this.codeblock? https://github.com/pieces-app/obsidian-pieces/blob/6efbdd9448e1f4df056021f3d44b2ec41f7ddb8a/main.js#L26917

**Comment by mason-at-pieces** [comment]
Hey @ajkdrag, sorry for the late reply again!

Is this still still occurring for you on the latest version of the plugin?

**Comment by caleb-at-pieces** [comment]
Hello @ajkdrag , thank you for bringing this to our attention! I've just pushed a build that should resolve this issue, please let me know if you have any more problems!

**Comment by ajkdrag** [comment]
Thanks for the fix. It's all good.

**Comment by mason-at-pieces** [comment]
Awesome, glad to hear!
