### ISSUE TITLE
Pieces Plugin Causes formatting issues in left side panel

### ISSUE THREAD

**Issue by freshminty** [pieces-app/obsidian-pieces#14]
Specifically interferes heavily with using Longform. The side panel 'tabs' in Longform become unusable as the formatting changes to vertical stacking which overlaps with other fields. Disabling and Re-enabling Pieces for Developers while having the Longform panel open will replicate the issue. 
![Pieces_Disabled_FormattingBug](https://github.com/pieces-app/obsidian-pieces/assets/4251926/4f18bfc4-5dc0-4016-9549-c19362305df6)
![Pieces_Enabled_FormattingBug](https://github.com/pieces-app/obsidian-pieces/assets/4251926/5f6f2e2d-d56d-4468-8519-23913057be12)

**Comment by mason-at-pieces** [comment]
Hey @freshminty, thanks for bringing this to light! We will absolutely look into the issues around this and get a solution released hopefully within the next week.

Going to tag @caleb-at-pieces, who is the lead dev for the plugin as well.

**Comment by caleb-at-pieces** [comment]
Hello @freshminty , thank you for bringing this to our attention! I just pushed a release to our plugin (version 1.6.1) that should fix this problem. I'm going to go ahead and close this issue now, please let me know if it's still broken!
