### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by techyogi** [pieces-app/obsidian-pieces#16]
Any reason the obsidian plugin using gpt-4 can't work on iOS mobile? Seems easy enough.

**Comment by mason-at-pieces** [comment]
Hey @techyogi! So the reason our plugin isn't compatible with mobile is because we require Pieces OS to be running which currently only runs on desktops.

**Comment by techyogi** [comment]
Any way I can at least access snippets and content on mobile then? Assumes they’d be in obsidian

**Comment by mason-at-pieces** [comment]
@techyogi Unfortunately Pieces isn't compatible with mobile at the moment, so sadly no.

This could change in the next few months so I will be sure to keep you updated if it does.
