### ISSUE TITLE
disappearing bullet list inside callouts

### ISSUE THREAD

**Issue by simo-corbo** [pieces-app/obsidian-pieces#17]
When the pieces plugin is activated, the bullet points inside callouts disappear.
With Pieces enabled:
<img width="639" alt="Screenshot 2024-01-27 at 11 49 21" src="https://github.com/pieces-app/obsidian-pieces/assets/126069316/5f3b57a9-9a02-43f2-ba50-b54958e85100">

With Pieces disabled:
<img width="639" alt="Screenshot 2024-01-27 at 11 49 09" src="https://github.com/pieces-app/obsidian-pieces/assets/126069316/1781c9c1-d9ec-4e22-a199-e9fc5afc5991">

**Comment by caleb-at-pieces** [comment]
Thanks for reaching out about this, I should be able to have a fix for this by the end of this week or start of next!

**Comment by ramarivera** [comment]
![Screenshot 2024-02-25 at 06 23 19](https://github.com/pieces-app/obsidian-pieces/assets/7547875/f61c9203-c851-4de0-aa1a-8fd64556600c)

Just wanted to comment that this is still happening, but not only with callouts :(

**Comment by caleb-at-pieces** [comment]
@simo-corbo @ramarivera sorry for delay here, just got around to this. It should be fixed in the next release (targeted for Thursday, February 29)

**Comment by simo-corbo** [comment]
Thank you :)

**Comment by caleb-at-pieces** [comment]
Just managed to get this out, sorry for being a bit late guys! Version 1.12.0 and on this issue should be fixed.
